# Generated by Django 6.0.2 on 2026-03-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='The Developer Behind the Code', max_length=200)),
                ('bio_text', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('github_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Bio / About Section',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
