# Generated by Django 6.0.2 on 2026-03-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio_App', '0002_bio_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='cv',
            field=models.FileField(blank=True, help_text='Upload your CV/Résumé (PDF format)', null=True, upload_to='cv/'),
        ),
    ]
