# Generated by Django 6.0.2 on 2026-03-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio_App', '0003_bio_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='hero_subtitle',
            field=models.TextField(default='Full Stack Developer specializing in high-performance Django applications and elegant user experiences.'),
        ),
        migrations.AddField(
            model_name='bio',
            name='hero_title',
            field=models.CharField(default='Building Digital Logic.', max_length=200),
        ),
    ]
