# Generated by Django 6.0.2 on 2026-03-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio_App', '0004_bio_hero_subtitle_bio_hero_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='facebook_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='full_name',
            field=models.CharField(default='David Kendric', max_length=200),
        ),
        migrations.AddField(
            model_name='bio',
            name='instagram_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='roles_list',
            field=models.CharField(default='Frontend Developer, Backend Enthusiast', help_text='Comma-separated roles for the typewriter effect', max_length=500),
        ),
        migrations.AddField(
            model_name='bio',
            name='twitter_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='hero_subtitle',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium, ab autem repellat reiciendis ipsam perspiciatis.'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='hero_title',
            field=models.CharField(default="Hello, It's Me", max_length=200),
        ),
    ]
