# Generated by Django 6.0.2 on 2026-03-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio_App', '0005_bio_facebook_link_bio_full_name_bio_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='about_role',
            field=models.CharField(default='Django & Python Architect!', max_length=200),
        ),
        migrations.AddField(
            model_name='bio',
            name='about_title',
            field=models.CharField(default='About Me', max_length=200),
        ),
        migrations.AlterField(
            model_name='bio',
            name='bio_text',
            field=models.TextField(default='I am a specialized Django & Python Architect focused on building high-performance backend systems. I turn complex business requirements into elegant, scalable digital solutions with a focus on security and efficiency.'),
        ),
    ]
