# Generated by Django 6.0.2 on 2026-03-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio_App', '0006_bio_about_role_bio_about_title_alter_bio_bio_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='about_title',
        ),
        migrations.AddField(
            model_name='bio',
            name='about_title_accent',
            field=models.CharField(default='Me', max_length=200),
        ),
        migrations.AddField(
            model_name='bio',
            name='about_title_main',
            field=models.CharField(default='About', max_length=200),
        ),
    ]
