# Generated by Django 6.0.2 on 2026-03-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio_App', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(blank=True, help_text='Detailed description for the project page'),
        ),
    ]
