# Generated by Django 6.0.2 on 2026-07-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio_App", "0010_contactmessage_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="bio",
            name="whatsapp_link",
            field=models.URLField(
                blank=True,
                help_text="Full WhatsApp link, e.g. https://wa.me/250781234567",
            ),
        ),
    ]
