# Generated by Django 6.0.2 on 2026-07-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio_App", "0011_bio_whatsapp_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. 'Certified Django Developer'", max_length=200
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        help_text="e.g. 'Coursera', 'AWS', 'University of Rwanda'",
                        max_length=200,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload the certificate as a PDF",
                        upload_to="certificates/",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
