# Generated by Django 6.0.2 on 2026-07-29 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio_App", "0012_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bio",
            name="cv",
            field=models.FileField(
                blank=True,
                help_text="Upload your CV/Résumé (PDF format only)",
                null=True,
                upload_to="cv/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
    ]
