# Generated by Django 6.0.2 on 2026-07-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio_App", "0013_alter_bio_cv"),
    ]

    operations = [
        migrations.AddField(
            model_name="bio",
            name="extra_bio_text",
            field=models.TextField(
                blank=True,
                help_text="Short personal paragraph revealed when a visitor clicks 'Read More' on the About section.",
            ),
        ),
    ]
