# Generated by Django 6.0.2 on 2026-07-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio_App", "0014_bio_extra_bio_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order"], "verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="skill",
            name="proficiency",
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Controls display order in the Technical Arsenal section",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(
                help_text="Enter with correct casing, e.g. 'PostgreSQL', 'REST APIs', 'DNS'",
                max_length=50,
            ),
        ),
    ]
