# Generated by Django 6.0.2 on 2026-07-29 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "myportfolio_App",
            "0015_alter_category_options_remove_skill_proficiency_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Service",
        ),
    ]
