# Generated by Django 6.0.2 on 2026-07-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio_App", "0016_delete_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="link",
        ),
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(
                blank=True, help_text="Link to the GitHub repository"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="live_link",
            field=models.URLField(
                blank=True, help_text="Link to the live/deployed site"
            ),
        ),
    ]
