# Generated by Django 6.0.2 on 2026-07-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myportfolio_App", "0017_remove_project_link_project_github_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bio",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Shown in Google search results and when the site is shared on social media. Keep it under ~160 characters. Falls back to the hero subtitle if left blank.",
                max_length=160,
            ),
        ),
    ]
